### ISSUE TITLE
Итоги 1 домашки

### ISSUE THREAD

**Issue by sergchepl** [Melisses/ITScholl_FirstProject#2]
### Ошибки
1. `<h1 class="main-article__title_h1">` Использован как модификатор, но на самом деле это элемент по БЭМу, так что `_h1` нужно убрать
2. `<article class="main-article article_aboutme">` article_aboutme - объявлен как модификатор  
                    `<ul class="article_aboutme__list">`
                        `<li class="article-aboutme__item">` используется как блок, от которого элемент зависит. Нужно было сразу объявить как article-aboutme, чтобы было понятно.
3. `<img src="assets/html.png" alt="" height="100px">` Лучше избегать атрибутов, style в тегах, они имеют слишком высокий приоритет.
4. `<section class="section main-section section-flax section_skills">` объявлено слишком много БЛОКов, которые потом не используются.
5. h1-6 нужно использовать для заголовков.

**Comment by Melisses** [comment]
**Работа над ошибками**

> 1. <h1 class="main-article__title_h1"> Использован как модификатор, но на самом деле это элемент по БЭМу, так что _h1 нужно убрать.
**Исправлено**

> 2. <article class="main-article article_aboutme"> article_aboutme - объявлен как модификатор
<ul class="article_aboutme__list">
<li class="article-aboutme__item"> используется как блок, от которого элемент зависит. Нужно было сразу объявить как article-aboutme, чтобы было понятно.
**Исправлено. Тут я невнимательно поставила подчёркивание, а не дефис.**

> 3. <img src="assets/html.png" alt="" height="100px"> Лучше избегать атрибутов, style в тегах, они имеют слишком высокий приоритет.
**Исправлено**

> 4. <section class="section main-section section-flax section_skills"> объявлено слишком много БЛОКов, которые потом не используются.
**Исправлено**

> h1-6 нужно использовать для заголовков.
**Учла. Подправила код**

**Comment by Melisses** [comment]
**Работа над ошибками**

<h1 class="main-article__title_h1"> Использован как модификатор, но на самом деле это элемент по БЭМу, так что _h1 нужно убрать
**Исправлено**

<article class="main-article article_aboutme"> article_aboutme - объявлен как модификатор
<ul class="article_aboutme__list">
<li class="article-aboutme__item"> используется как блок, от которого элемент зависит. Нужно было сразу объявить как article-aboutme, чтобы было понятно.
**Исправлено**

<img src="assets/html.png" alt="" height="100px"> Лучше избегать атрибутов, style в тегах, они имеют слишком высокий приоритет.
**Исправлено**

<section class="section main-section section-flax section_skills"> объявлено слишком много БЛОКов, которые потом не используются.
**Исправлено**

h1-6 нужно использовать для заголовков.
**Учла. Исправлено**

**Comment by Melisses** [comment]
Выполнена работа над ошибками. Учтены и исправлены все 5 пунктов.
